ALTER TABLE IF EXISTS INSTRUMENTS
    ALTER COLUMN ID ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS INSTRUMENT_FOCUS
    ALTER COLUMN INSTRUMENT_ID ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS EXERCISES
    ALTER COLUMN INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS JOURNAL_ENTRIES
    ALTER COLUMN INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS PLAN_ACTIVITIES
    ALTER COLUMN INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS PRACTICE_SESSIONS
    ALTER COLUMN INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS SKILL_INSTRUMENTS
    ALTER COLUMN INSTRUMENTS ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS SONGS
    ALTER COLUMN INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
ALTER TABLE IF EXISTS USER_PREFERENCES
    ALTER COLUMN PRIMARY_INSTRUMENT ENUM('GUITAR', 'ACOUSTIC', 'KEYS', 'DRUMS');
