/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessaoRouteImport } from './routes/sessao'
import { Route as IndexRouteImport } from './routes/index'

const SessaoRoute = SessaoRouteImport.update({
  id: '/sessao',
  path: '/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessao': typeof SessaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessao': typeof SessaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessao': typeof SessaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sessao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sessao'
  id: '__root__' | '/' | '/sessao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessaoRoute: typeof SessaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessao': {
      id: '/sessao'
      path: '/sessao'
      fullPath: '/sessao'
      preLoaderRoute: typeof SessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessaoRoute: SessaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
