/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MetronomoRouteImport } from './routes/metronomo'
import { Route as OuvidoRouteImport } from './routes/ouvido'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RepertorioRouteImport } from './routes/repertorio'
import { Route as SessaoRouteImport } from './routes/sessao'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TreinoMusicaRouteImport } from './routes/treino-musica'
import { Route as BibliotecaNodeIdRouteImport } from './routes/biblioteca.$nodeId'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'
import { Route as RepertorioSongIdRouteImport } from './routes/repertorio.$songId'
import { Route as TreinoMusicaSongIdInstrumentRouteImport } from './routes/treino-musica.$songId.$instrument'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomoRoute = MetronomoRouteImport.update({
  id: '/metronomo',
  path: '/metronomo',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoRoute = OuvidoRouteImport.update({
  id: '/ouvido',
  path: '/ouvido',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioRoute = RepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoRoute = SessaoRouteImport.update({
  id: '/sessao',
  path: '/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoMusicaRoute = TreinoMusicaRouteImport.update({
  id: '/treino-musica',
  path: '/treino-musica',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaNodeIdRoute = BibliotecaNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => BibliotecaRoute,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjetosRoute,
} as any)
const RepertorioSongIdRoute = RepertorioSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => RepertorioRoute,
} as any)
const TreinoMusicaSongIdInstrumentRoute =
  TreinoMusicaSongIdInstrumentRouteImport.update({
    id: '/$songId/$instrument',
    path: '/$songId/$instrument',
    getParentRoute: () => TreinoMusicaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/exercicios': typeof ExerciciosRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/exercicios': typeof ExerciciosRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/exercicios': typeof ExerciciosRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/exercicios'
    | '/mapa'
    | '/metronomo'
    | '/ouvido'
    | '/plano'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/treino-musica/$songId/$instrument'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/exercicios'
    | '/mapa'
    | '/metronomo'
    | '/ouvido'
    | '/plano'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/treino-musica/$songId/$instrument'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/exercicios'
    | '/mapa'
    | '/metronomo'
    | '/ouvido'
    | '/plano'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/treino-musica/$songId/$instrument'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  DadosRoute: typeof DadosRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiarioRoute: typeof DiarioRoute
  ExerciciosRoute: typeof ExerciciosRoute
  MapaRoute: typeof MapaRoute
  MetronomoRoute: typeof MetronomoRoute
  OuvidoRoute: typeof OuvidoRoute
  PlanoRoute: typeof PlanoRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  RepertorioRoute: typeof RepertorioRouteWithChildren
  SessaoRoute: typeof SessaoRoute
  SkillsRoute: typeof SkillsRoute
  TreinoMusicaRoute: typeof TreinoMusicaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronomo': {
      id: '/metronomo'
      path: '/metronomo'
      fullPath: '/metronomo'
      preLoaderRoute: typeof MetronomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvido': {
      id: '/ouvido'
      path: '/ouvido'
      fullPath: '/ouvido'
      preLoaderRoute: typeof OuvidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio': {
      id: '/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof RepertorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao': {
      id: '/sessao'
      path: '/sessao'
      fullPath: '/sessao'
      preLoaderRoute: typeof SessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-musica': {
      id: '/treino-musica'
      path: '/treino-musica'
      fullPath: '/treino-musica'
      preLoaderRoute: typeof TreinoMusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$nodeId': {
      id: '/biblioteca/$nodeId'
      path: '/$nodeId'
      fullPath: '/biblioteca/$nodeId'
      preLoaderRoute: typeof BibliotecaNodeIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/repertorio/$songId': {
      id: '/repertorio/$songId'
      path: '/$songId'
      fullPath: '/repertorio/$songId'
      preLoaderRoute: typeof RepertorioSongIdRouteImport
      parentRoute: typeof RepertorioRoute
    }
    '/treino-musica/$songId/$instrument': {
      id: '/treino-musica/$songId/$instrument'
      path: '/$songId/$instrument'
      fullPath: '/treino-musica/$songId/$instrument'
      preLoaderRoute: typeof TreinoMusicaSongIdInstrumentRouteImport
      parentRoute: typeof TreinoMusicaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaNodeIdRoute: typeof BibliotecaNodeIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaNodeIdRoute: BibliotecaNodeIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface RepertorioRouteChildren {
  RepertorioSongIdRoute: typeof RepertorioSongIdRoute
}

const RepertorioRouteChildren: RepertorioRouteChildren = {
  RepertorioSongIdRoute: RepertorioSongIdRoute,
}

const RepertorioRouteWithChildren = RepertorioRoute._addFileChildren(
  RepertorioRouteChildren,
)

interface TreinoMusicaRouteChildren {
  TreinoMusicaSongIdInstrumentRoute: typeof TreinoMusicaSongIdInstrumentRoute
}

const TreinoMusicaRouteChildren: TreinoMusicaRouteChildren = {
  TreinoMusicaSongIdInstrumentRoute: TreinoMusicaSongIdInstrumentRoute,
}

const TreinoMusicaRouteWithChildren = TreinoMusicaRoute._addFileChildren(
  TreinoMusicaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  DadosRoute: DadosRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiarioRoute: DiarioRoute,
  ExerciciosRoute: ExerciciosRoute,
  MapaRoute: MapaRoute,
  MetronomoRoute: MetronomoRoute,
  OuvidoRoute: OuvidoRoute,
  PlanoRoute: PlanoRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  RepertorioRoute: RepertorioRouteWithChildren,
  SessaoRoute: SessaoRoute,
  SkillsRoute: SkillsRoute,
  TreinoMusicaRoute: TreinoMusicaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
