/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as DadosRouteImport } from './routes/dados'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MetronomoRouteImport } from './routes/metronomo'
import { Route as MusicasRouteImport } from './routes/musicas'
import { Route as OuvidoRouteImport } from './routes/ouvido'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PraticaRouteImport } from './routes/pratica'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RepertorioRouteImport } from './routes/repertorio'
import { Route as SessaoRouteImport } from './routes/sessao'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TreinoMusicaRouteImport } from './routes/treino-musica'
import { Route as BibliotecaNodeIdRouteImport } from './routes/biblioteca.$nodeId'
import { Route as ExerciciosExerciseIdRouteImport } from './routes/exercicios.$exerciseId'
import { Route as MissoesMissionIdRouteImport } from './routes/missoes.$missionId'
import { Route as MusicasSongIdRouteImport } from './routes/musicas.$songId'
import { Route as ProjetosProjectIdRouteImport } from './routes/projetos.$projectId'
import { Route as RepertorioSongIdRouteImport } from './routes/repertorio.$songId'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioStudioProjectIdRouteImport } from './routes/studio.$studioProjectId'
import { Route as TreinoMusicaSongIdInstrumentRouteImport } from './routes/treino-musica.$songId.$instrument'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const DadosRoute = DadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomoRoute = MetronomoRouteImport.update({
  id: '/metronomo',
  path: '/metronomo',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasRoute = MusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => rootRouteImport,
} as any)
const OuvidoRoute = OuvidoRouteImport.update({
  id: '/ouvido',
  path: '/ouvido',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticaRoute = PraticaRouteImport.update({
  id: '/pratica',
  path: '/pratica',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioRoute = RepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => rootRouteImport,
} as any)
const SessaoRoute = SessaoRouteImport.update({
  id: '/sessao',
  path: '/sessao',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoMusicaRoute = TreinoMusicaRouteImport.update({
  id: '/treino-musica',
  path: '/treino-musica',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaNodeIdRoute = BibliotecaNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => BibliotecaRoute,
} as any)
const ExerciciosExerciseIdRoute = ExerciciosExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => ExerciciosRoute,
} as any)
const MissoesMissionIdRoute = MissoesMissionIdRouteImport.update({
  id: '/missoes/$missionId',
  path: '/missoes/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasSongIdRoute = MusicasSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => MusicasRoute,
} as any)
const ProjetosProjectIdRoute = ProjetosProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjetosRoute,
} as any)
const RepertorioSongIdRoute = RepertorioSongIdRouteImport.update({
  id: '/$songId',
  path: '/$songId',
  getParentRoute: () => RepertorioRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioStudioProjectIdRoute = StudioStudioProjectIdRouteImport.update({
  id: '/$studioProjectId',
  path: '/$studioProjectId',
  getParentRoute: () => StudioRoute,
} as any)
const TreinoMusicaSongIdInstrumentRoute =
  TreinoMusicaSongIdInstrumentRouteImport.update({
    id: '/$songId/$instrument',
    path: '/$songId/$instrument',
    getParentRoute: () => TreinoMusicaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/editor': typeof EditorRoute
  '/exercicios': typeof ExerciciosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/musicas': typeof MusicasRouteWithChildren
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/pratica': typeof PraticaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRouteWithChildren
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/exercicios/$exerciseId': typeof ExerciciosExerciseIdRoute
  '/missoes/$missionId': typeof MissoesMissionIdRoute
  '/musicas/$songId': typeof MusicasSongIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/studio/$studioProjectId': typeof StudioStudioProjectIdRoute
  '/studio/': typeof StudioIndexRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/editor': typeof EditorRoute
  '/exercicios': typeof ExerciciosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/musicas': typeof MusicasRouteWithChildren
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/pratica': typeof PraticaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/exercicios/$exerciseId': typeof ExerciciosExerciseIdRoute
  '/missoes/$missionId': typeof MissoesMissionIdRoute
  '/musicas/$songId': typeof MusicasSongIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/studio/$studioProjectId': typeof StudioStudioProjectIdRoute
  '/studio': typeof StudioIndexRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/dados': typeof DadosRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/editor': typeof EditorRoute
  '/exercicios': typeof ExerciciosRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/historico': typeof HistoricoRoute
  '/jornada': typeof JornadaRoute
  '/mapa': typeof MapaRoute
  '/metronomo': typeof MetronomoRoute
  '/musicas': typeof MusicasRouteWithChildren
  '/ouvido': typeof OuvidoRoute
  '/plano': typeof PlanoRoute
  '/pratica': typeof PraticaRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/repertorio': typeof RepertorioRouteWithChildren
  '/sessao': typeof SessaoRoute
  '/skills': typeof SkillsRoute
  '/studio': typeof StudioRouteWithChildren
  '/treino-musica': typeof TreinoMusicaRouteWithChildren
  '/biblioteca/$nodeId': typeof BibliotecaNodeIdRoute
  '/exercicios/$exerciseId': typeof ExerciciosExerciseIdRoute
  '/missoes/$missionId': typeof MissoesMissionIdRoute
  '/musicas/$songId': typeof MusicasSongIdRoute
  '/projetos/$projectId': typeof ProjetosProjectIdRoute
  '/repertorio/$songId': typeof RepertorioSongIdRoute
  '/studio/$studioProjectId': typeof StudioStudioProjectIdRoute
  '/studio/': typeof StudioIndexRoute
  '/treino-musica/$songId/$instrument': typeof TreinoMusicaSongIdInstrumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/editor'
    | '/exercicios'
    | '/explorar'
    | '/historico'
    | '/jornada'
    | '/mapa'
    | '/metronomo'
    | '/musicas'
    | '/ouvido'
    | '/plano'
    | '/pratica'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/studio'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/exercicios/$exerciseId'
    | '/missoes/$missionId'
    | '/musicas/$songId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/studio/$studioProjectId'
    | '/studio/'
    | '/treino-musica/$songId/$instrument'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/editor'
    | '/exercicios'
    | '/explorar'
    | '/historico'
    | '/jornada'
    | '/mapa'
    | '/metronomo'
    | '/musicas'
    | '/ouvido'
    | '/plano'
    | '/pratica'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/exercicios/$exerciseId'
    | '/missoes/$missionId'
    | '/musicas/$songId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/studio/$studioProjectId'
    | '/studio'
    | '/treino-musica/$songId/$instrument'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/dados'
    | '/diagnostico'
    | '/diario'
    | '/editor'
    | '/exercicios'
    | '/explorar'
    | '/historico'
    | '/jornada'
    | '/mapa'
    | '/metronomo'
    | '/musicas'
    | '/ouvido'
    | '/plano'
    | '/pratica'
    | '/projetos'
    | '/repertorio'
    | '/sessao'
    | '/skills'
    | '/studio'
    | '/treino-musica'
    | '/biblioteca/$nodeId'
    | '/exercicios/$exerciseId'
    | '/missoes/$missionId'
    | '/musicas/$songId'
    | '/projetos/$projectId'
    | '/repertorio/$songId'
    | '/studio/$studioProjectId'
    | '/studio/'
    | '/treino-musica/$songId/$instrument'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  DadosRoute: typeof DadosRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiarioRoute: typeof DiarioRoute
  EditorRoute: typeof EditorRoute
  ExerciciosRoute: typeof ExerciciosRouteWithChildren
  ExplorarRoute: typeof ExplorarRoute
  HistoricoRoute: typeof HistoricoRoute
  JornadaRoute: typeof JornadaRoute
  MapaRoute: typeof MapaRoute
  MetronomoRoute: typeof MetronomoRoute
  MusicasRoute: typeof MusicasRouteWithChildren
  OuvidoRoute: typeof OuvidoRoute
  PlanoRoute: typeof PlanoRoute
  PraticaRoute: typeof PraticaRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  RepertorioRoute: typeof RepertorioRouteWithChildren
  SessaoRoute: typeof SessaoRoute
  SkillsRoute: typeof SkillsRoute
  StudioRoute: typeof StudioRouteWithChildren
  TreinoMusicaRoute: typeof TreinoMusicaRouteWithChildren
  MissoesMissionIdRoute: typeof MissoesMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dados': {
      id: '/dados'
      path: '/dados'
      fullPath: '/dados'
      preLoaderRoute: typeof DadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronomo': {
      id: '/metronomo'
      path: '/metronomo'
      fullPath: '/metronomo'
      preLoaderRoute: typeof MetronomoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas': {
      id: '/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof MusicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ouvido': {
      id: '/ouvido'
      path: '/ouvido'
      fullPath: '/ouvido'
      preLoaderRoute: typeof OuvidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pratica': {
      id: '/pratica'
      path: '/pratica'
      fullPath: '/pratica'
      preLoaderRoute: typeof PraticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio': {
      id: '/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof RepertorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessao': {
      id: '/sessao'
      path: '/sessao'
      fullPath: '/sessao'
      preLoaderRoute: typeof SessaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino-musica': {
      id: '/treino-musica'
      path: '/treino-musica'
      fullPath: '/treino-musica'
      preLoaderRoute: typeof TreinoMusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$nodeId': {
      id: '/biblioteca/$nodeId'
      path: '/$nodeId'
      fullPath: '/biblioteca/$nodeId'
      preLoaderRoute: typeof BibliotecaNodeIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/exercicios/$exerciseId': {
      id: '/exercicios/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/exercicios/$exerciseId'
      preLoaderRoute: typeof ExerciciosExerciseIdRouteImport
      parentRoute: typeof ExerciciosRoute
    }
    '/missoes/$missionId': {
      id: '/missoes/$missionId'
      path: '/missoes/$missionId'
      fullPath: '/missoes/$missionId'
      preLoaderRoute: typeof MissoesMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas/$songId': {
      id: '/musicas/$songId'
      path: '/$songId'
      fullPath: '/musicas/$songId'
      preLoaderRoute: typeof MusicasSongIdRouteImport
      parentRoute: typeof MusicasRoute
    }
    '/projetos/$projectId': {
      id: '/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof ProjetosProjectIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/repertorio/$songId': {
      id: '/repertorio/$songId'
      path: '/$songId'
      fullPath: '/repertorio/$songId'
      preLoaderRoute: typeof RepertorioSongIdRouteImport
      parentRoute: typeof RepertorioRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$studioProjectId': {
      id: '/studio/$studioProjectId'
      path: '/$studioProjectId'
      fullPath: '/studio/$studioProjectId'
      preLoaderRoute: typeof StudioStudioProjectIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/treino-musica/$songId/$instrument': {
      id: '/treino-musica/$songId/$instrument'
      path: '/$songId/$instrument'
      fullPath: '/treino-musica/$songId/$instrument'
      preLoaderRoute: typeof TreinoMusicaSongIdInstrumentRouteImport
      parentRoute: typeof TreinoMusicaRoute
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaNodeIdRoute: typeof BibliotecaNodeIdRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaNodeIdRoute: BibliotecaNodeIdRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface ExerciciosRouteChildren {
  ExerciciosExerciseIdRoute: typeof ExerciciosExerciseIdRoute
}

const ExerciciosRouteChildren: ExerciciosRouteChildren = {
  ExerciciosExerciseIdRoute: ExerciciosExerciseIdRoute,
}

const ExerciciosRouteWithChildren = ExerciciosRoute._addFileChildren(
  ExerciciosRouteChildren,
)

interface MusicasRouteChildren {
  MusicasSongIdRoute: typeof MusicasSongIdRoute
}

const MusicasRouteChildren: MusicasRouteChildren = {
  MusicasSongIdRoute: MusicasSongIdRoute,
}

const MusicasRouteWithChildren =
  MusicasRoute._addFileChildren(MusicasRouteChildren)

interface ProjetosRouteChildren {
  ProjetosProjectIdRoute: typeof ProjetosProjectIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosProjectIdRoute: ProjetosProjectIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

interface RepertorioRouteChildren {
  RepertorioSongIdRoute: typeof RepertorioSongIdRoute
}

const RepertorioRouteChildren: RepertorioRouteChildren = {
  RepertorioSongIdRoute: RepertorioSongIdRoute,
}

const RepertorioRouteWithChildren = RepertorioRoute._addFileChildren(
  RepertorioRouteChildren,
)

interface StudioRouteChildren {
  StudioStudioProjectIdRoute: typeof StudioStudioProjectIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioStudioProjectIdRoute: StudioStudioProjectIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface TreinoMusicaRouteChildren {
  TreinoMusicaSongIdInstrumentRoute: typeof TreinoMusicaSongIdInstrumentRoute
}

const TreinoMusicaRouteChildren: TreinoMusicaRouteChildren = {
  TreinoMusicaSongIdInstrumentRoute: TreinoMusicaSongIdInstrumentRoute,
}

const TreinoMusicaRouteWithChildren = TreinoMusicaRoute._addFileChildren(
  TreinoMusicaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  DadosRoute: DadosRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiarioRoute: DiarioRoute,
  EditorRoute: EditorRoute,
  ExerciciosRoute: ExerciciosRouteWithChildren,
  ExplorarRoute: ExplorarRoute,
  HistoricoRoute: HistoricoRoute,
  JornadaRoute: JornadaRoute,
  MapaRoute: MapaRoute,
  MetronomoRoute: MetronomoRoute,
  MusicasRoute: MusicasRouteWithChildren,
  OuvidoRoute: OuvidoRoute,
  PlanoRoute: PlanoRoute,
  PraticaRoute: PraticaRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  RepertorioRoute: RepertorioRouteWithChildren,
  SessaoRoute: SessaoRoute,
  SkillsRoute: SkillsRoute,
  StudioRoute: StudioRouteWithChildren,
  TreinoMusicaRoute: TreinoMusicaRouteWithChildren,
  MissoesMissionIdRoute: MissoesMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
