package com.musicos.config;

import com.musicos.domain.Assessment;
import com.musicos.domain.DifficultyDemand;
import com.musicos.domain.Exercise;
import com.musicos.domain.ExerciseVariation;
import com.musicos.domain.InstrumentId;
import com.musicos.domain.LearningStage;
import java.util.List;

/** Primeira jornada editorial: pouca quantidade, sequência musical explícita e sem progresso simulado. */
final class FirstJourneyCatalog {
    private FirstJourneyCatalog() {}

    static List<Exercise> exercises() {
        return List.of(
                exercise("journey-guitar-pulse-riff", "Encontrar o pulso dentro de um riff", "Pulso",
                        InstrumentId.GUITAR, "pulse", "imitate", 60, 76, 7,
                        "Marcar o pulso antes de tocar e manter quatro entradas do riff equidistantes.",
                        "Clique em 60 BPM; riff em uma corda; dois compassos marcando e dois tocando.",
                        "Quatro ciclos sem antecipar a primeira nota nem encurtar o silêncio.",
                        List.of("Ouça oito cliques sem tocar e marque o pé.",
                                "Cante o ritmo do riff mantendo o pé.",
                                "Toque dois compassos e atravesse um compasso de silêncio sem perder a volta."),
                        List.of(variation("Só pulso", "Abafe as cordas e ataque apenas no primeiro tempo.", -8, 3),
                                variation("Riff completo", "Use o riff principal de Seven Nation Army sem acelerar as notas repetidas.", 0, 4)),
                        "Seven Nation Army guitarra riff lento"),
                exercise("journey-guitar-note-landmarks", "Três referências no braço", "Notas no braço",
                        InstrumentId.GUITAR, "notes", "recall", 0, 0, 7,
                        "Encontrar E, A e C em duas regiões sem seguir um desenho decorado.",
                        "Sem metrônomo; cordas E e A; nomeie a nota antes de tocá-la.",
                        "Seis localizações corretas em ordem misturada, com conferência pelo som.",
                        List.of("Localize as cordas soltas E e A e cante cada nome.",
                                "Encontre C na corda A e E na corda D.",
                                "Misture seis pedidos e responda antes de olhar qualquer diagrama."),
                        List.of(variation("Com mapa", "Aponte cada casa no diagrama antes de tocar.", 0, 3),
                                variation("Sem mapa", "Responda aos seis pedidos em ordem aleatória.", 0, 4)), null),
                exercise("journey-guitar-eighth-riff", "Semínimas e colcheias no mesmo riff", "Subdivisões",
                        InstrumentId.GUITAR, "subdivisions", "context", 64, 88, 8,
                        "Alternar um compasso de semínimas e um de colcheias sem mudar o pulso.",
                        "64 BPM; uma nota abafada; conte '1 e 2 e 3 e 4 e' durante toda a forma.",
                        "Três formas completas com números estáveis e os 'e' exatamente no meio.",
                        List.of("Toque somente as semínimas enquanto conta também os 'e'.",
                                "Toque colcheias sem mover o pé duas vezes mais rápido.",
                                "Alterne os dois compassos e termine no primeiro tempo seguinte."),
                        List.of(variation("Uma nota", "Use uma única nota abafada nos dois compassos.", -8, 3),
                                variation("Duas cordas", "Distribua as colcheias entre E e A sem reiniciar a palheta.", 0, 5)),
                        "Zombie guitarra base simplificada"),
                exercise("journey-guitar-major-home", "Ouvir a tônica antes da frase", "Escala maior",
                        InstrumentId.GUITAR, "major-scale", "listen", 56, 76, 8,
                        "Distinguir tensão e repouso e encerrar uma frase curta na tônica.",
                        "Escala de C em uma região; referência de C antes de cada tentativa; quatro notas por frase.",
                        "Três respostas diferentes que terminam em C e soam concluídas para o estudante.",
                        List.of("Ouça C–B e cante a resolução antes de tocar C.",
                                "Escolha quatro notas da escala e deixe um tempo de silêncio.",
                                "Responda à frase terminando em C; depois compare com uma chegada em B."),
                        List.of(variation("Duas notas", "Compare somente B–C e G–C.", 0, 3),
                                variation("Pergunta e resposta", "Crie duas frases; apenas a resposta termina em C.", 0, 5)), null),
                exercise("journey-guitar-harmony-riff", "Riff sobre repouso, movimento e tensão", "Função harmônica",
                        InstrumentId.GUITAR, "harmonic-field", "transfer", 60, 80, 10,
                        "Criar um motivo que atravesse C, F e G sem perder a sensação de função.",
                        "Loop I–IV–V–I em C; uma ou duas notas por acorde; 60 BPM.",
                        "Duas voltas em que a frase chega a C junto com o retorno harmônico.",
                        List.of("Ouça C–F–G–C e descreva onde há repouso e tensão.",
                                "Toque uma nota-alvo diferente sobre cada acorde.",
                                "Repita o motivo e altere apenas a chegada sobre C."),
                        List.of(variation("Notas-alvo", "Use E sobre C, A sobre F e B sobre G.", -4, 4),
                                variation("Motivo próprio", "Mantenha o ritmo e mude as alturas na segunda volta.", 0, 6)),
                        "Zombie guitarra quatro acordes backing track"),
                exercise("journey-guitar-pulse-review", "Riff de memória depois do silêncio", "Retenção de pulso",
                        InstrumentId.GUITAR, "pulse", "recall", 60, 76, 6,
                        "Retomar pulso e riff sem contagem visual depois de um intervalo silencioso.",
                        "Ouça dois compassos, silencie dois e grave a volta sem reiniciar.",
                        "Três retornos no primeiro tempo; resultado inconclusivo se a grade não puder ser ouvida.",
                        List.of("Marque dois compassos com o clique.", "Atravesse dois compassos sem som.",
                                "Entre com o riff e confira a chegada contra o clique que retorna."),
                        List.of(variation("Silêncio curto", "Use um compasso sem clique.", 0, 3),
                                variation("Silêncio longo", "Use quatro compassos sem clique.", 0, 3)),
                        "Seven Nation Army guitarra riff"),

                exercise("journey-acoustic-pulse-strum", "Levada que atravessa o silêncio", "Pulso no violão",
                        InstrumentId.ACOUSTIC, "pulse", "imitate", 56, 72, 7,
                        "Manter a mão de levada em movimento mesmo quando o acorde não soa.",
                        "Em abafado; semínimas a 56 BPM; um compasso tocado e um com ataques omitidos.",
                        "Quatro ciclos sem parar a mão nem antecipar o retorno do som.",
                        List.of("Balance a mão sem tocar e conte quatro tempos.",
                                "Ataque apenas 1 e 3 sem interromper o movimento.",
                                "Toque um compasso, omita outro e retorne no tempo 1."),
                        List.of(variation("Mão muda", "Faça o movimento sem encostar nas cordas.", -8, 3),
                                variation("Acorde real", "Use Em e preserve o mesmo arco da mão.", 0, 4)),
                        "A Horse with No Name violão backing track"),
                exercise("journey-acoustic-bass-roots", "Baixos que anunciam o acorde", "Notas no violão",
                        InstrumentId.ACOUSTIC, "notes", "context", 52, 68, 7,
                        "Encontrar e tocar as fundamentais E, G, C e D antes de montar o acorde.",
                        "Cordas graves; uma fundamental por compasso; diga o nome antes do ataque.",
                        "Duas voltas E–G–C–D sem procurar por tentativa e erro.",
                        List.of("Localize E e G na sexta corda.", "Localize C e D na quinta corda.",
                                "Toque a sequência e deixe cada nota sustentar quatro tempos."),
                        List.of(variation("Duas raízes", "Alterne somente E e G.", 0, 3),
                                variation("Com acordes", "Depois do baixo, monte o acorde correspondente.", 0, 4)), null),
                exercise("journey-acoustic-eighth-strum", "Oitavas contínuas com acentos", "Subdivisões na levada",
                        InstrumentId.ACOUSTIC, "subdivisions", "context", 60, 84, 8,
                        "Tocar colcheias contínuas e destacar 2 e 4 sem deformar os ataques fracos.",
                        "Em; 60 BPM; movimento para baixo e para cima; acentos apenas em 2 e 4.",
                        "Oito compassos com distância regular entre ataques e acentos audíveis.",
                        List.of("Conte números e 'e' com a mão em movimento.",
                                "Abafe as cordas e acentue 2 e 4.", "Volte a Em mantendo o mesmo desenho."),
                        List.of(variation("Abafado", "Use as cordas abafadas para separar ritmo de acorde.", -8, 3),
                                variation("Dois acordes", "Alterne Em e G a cada dois compassos.", 0, 5)),
                        "Have You Ever Seen the Rain violão levada lenta"),
                exercise("journey-acoustic-major-melody", "Melodia cantada sobre um acorde", "Escala maior aplicada",
                        InstrumentId.ACOUSTIC, "major-scale", "listen", 0, 0, 8,
                        "Cantar e encontrar uma resposta de três notas que repousa na tônica.",
                        "Acorde C sustentado; voz primeiro; depois notas C, D, E, G no instrumento.",
                        "Duas respostas cantadas e reproduzidas, ambas terminando em C.",
                        List.of("Toque C e cante C–D–E–C.", "Crie outra resposta somente com C, D, E e G.",
                                "Encontre a frase no violão sem trocar o ritmo cantado."),
                        List.of(variation("Eco", "Imite C–D–E–C exatamente.", 0, 3),
                                variation("Resposta própria", "Mude duas notas, mas preserve a chegada em C.", 0, 5)), null),
                exercise("journey-acoustic-harmonic-cycle", "Ouvir a função no ciclo de quatro acordes", "Campo harmônico",
                        InstrumentId.ACOUSTIC, "harmonic-field", "song", 60, 76, 10,
                        "Relacionar repouso, movimento e tensão a C–G–Am–F enquanto acompanha.",
                        "Uma semínima por tempo; formas simplificadas; 60 BPM; quatro voltas sem interrupção.",
                        "Nomear a função percebida e sustentar quatro voltas com retorno claro a C.",
                        List.of("Ouça o ciclo e aponte onde ele poderia terminar.",
                                "Toque apenas o primeiro ataque de cada acorde.",
                                "Complete quatro voltas e reduza a dinâmica na última."),
                        List.of(variation("Um ataque", "Toque cada acorde somente no tempo 1.", -8, 4),
                                variation("Levada", "Use colcheias leves sem cobrir a mudança harmônica.", 0, 6)),
                        "Stand by Me violão quatro acordes"),
                exercise("journey-acoustic-chords-review", "Em e G sem cifra", "Retenção de acordes abertos",
                        InstrumentId.ACOUSTIC, "open-chords", "recall", 52, 68, 6,
                        "Reconstruir Em e G de memória e iniciar a troca no pulso.",
                        "Cifra fechada; quatro compassos por acorde; uma única tentativa de preparação.",
                        "Todas as cordas previstas audíveis e quatro trocas que chegam no tempo 1.",
                        List.of("Nomeie as notas graves de Em e G.", "Monte cada forma sem consultar o desenho.",
                                "Alterne por oito compassos e só então confira a cifra."),
                        List.of(variation("Conferência tardia", "Consulte a cifra apenas depois da primeira tomada.", 0, 3),
                                variation("Canção", "Use o ciclo de A Horse with No Name sem parar.", 0, 3)),
                        "A Horse with No Name violão"),

                exercise("journey-keys-pulse-note", "Uma nota que não perde a caminhada", "Pulso no teclado",
                        InstrumentId.KEYS, "pulse", "imitate", 60, 76, 7,
                        "Repetir C no pulso e manter a distância durante um compasso silencioso.",
                        "C central; semínimas a 60 BPM; mão direita; som desligado no terceiro compasso.",
                        "Três retornos alinhados ao primeiro tempo sem ataque compensatório.",
                        List.of("Toque C por oito pulsos e conte.", "Continue o gesto por quatro pulsos sem som.",
                                "Retorne no primeiro tempo e preserve o mesmo volume."),
                        List.of(variation("Dedo 2", "Repita com D e o dedo 2.", 0, 3),
                                variation("Riff", "Use o ritmo de Seven Nation Army em uma nota.", 0, 4)),
                        "Seven Nation Army teclado riff"),
                exercise("journey-keys-landmarks", "C, F e G sem contar teclas", "Mapa do teclado",
                        InstrumentId.KEYS, "notes", "recall", 0, 0, 7,
                        "Encontrar C, F e G em três oitavas pela geometria das teclas pretas.",
                        "Sem etiquetas; mãos alternadas; nomeie antes de tocar.",
                        "Nove localizações corretas em ordem misturada, sem contagem desde C.",
                        List.of("Encontre C à esquerda de cada grupo de duas teclas pretas.",
                                "Use o grupo de três para localizar F e G.",
                                "Peça as nove notas em ordem aleatória e responda com mãos alternadas."),
                        List.of(variation("Uma oitava", "Restrinja a busca à região central.", 0, 3),
                                variation("Três oitavas", "Alterne grave, médio e agudo sem repetir a ordem.", 0, 4)), null),
                exercise("journey-keys-subdivision-hands", "Pulso na esquerda, colcheias na direita", "Subdivisões entre mãos",
                        InstrumentId.KEYS, "subdivisions", "context", 56, 76, 8,
                        "Manter semínimas na esquerda enquanto a direita divide cada pulso em duas notas.",
                        "Esquerda em C; direita C–D; 56 BPM; sem pedal; quatro compassos.",
                        "Três séries com a esquerda estável e duas notas direitas por pulso.",
                        List.of("Toque apenas C com a esquerda em semínimas.",
                                "Conte '1 e' e acrescente C–D na direita.",
                                "Retire a direita por um compasso e recoloque sem alterar a esquerda."),
                        List.of(variation("Mãos separadas", "Faça cada função isoladamente.", -8, 3),
                                variation("Frase", "Troque C–D por E–D sem alterar o ritmo.", 0, 5)), null),
                exercise("journey-keys-major-answer", "Pergunta e resposta com chegada em C", "Escala maior",
                        InstrumentId.KEYS, "major-scale", "transfer", 60, 80, 8,
                        "Criar duas frases usando C maior e reservar a tônica para a resposta.",
                        "Mão direita; cinco notas C–G; 60 BPM; dois compassos por frase e um tempo de pausa.",
                        "Duas execuções da forma com ritmo repetível, pausa clara e resposta em C.",
                        List.of("Toque C–D–E–G como pergunta e pare um tempo.",
                                "Responda G–E–D–C.", "Mude as alturas, preserve o ritmo e a chegada."),
                        List.of(variation("Modelo", "Repita exatamente a pergunta e resposta propostas.", -4, 3),
                                variation("Autoria", "Crie outra dupla mantendo o mesmo tamanho.", 0, 5)),
                        "Ode to Joy teclado melodia fácil"),
                exercise("journey-keys-harmonic-functions", "Baixo e tríade mostram a função", "Campo harmônico no teclado",
                        InstrumentId.KEYS, "harmonic-field", "song", 60, 76, 10,
                        "Tocar C–F–G–C e reconhecer repouso, movimento e tensão pelo som.",
                        "Baixo na esquerda e tríade na direita; um acorde por compasso; sem pedal.",
                        "Quatro voltas sem notas omitidas e uma descrição coerente das três funções.",
                        List.of("Toque apenas os baixos C–F–G–C.", "Acrescente tríades em posição fundamental.",
                                "Na última volta, pare em G e cante a resolução antes de tocar C."),
                        List.of(variation("Shell", "Use apenas fundamental e terça na mão direita.", -8, 4),
                                variation("Canção", "Aplique as funções aos acordes simplificados de Let It Be.", 0, 6)),
                        "Let It Be teclado acordes backing track"),
                exercise("journey-keys-five-review", "Cinco dedos em outra tonalidade", "Retenção e transferência",
                        InstrumentId.KEYS, "five-finger-position", "recall", 56, 72, 6,
                        "Reconstruir a posição de cinco dedos em G sem consultar numeração.",
                        "Mão direita; G–A–B–C–D; sem pedal; uma subida, pausa e descida.",
                        "Três voltas uniformes e dedilhado explicado depois da execução.",
                        List.of("Feche o material e encontre G.", "Posicione os cinco dedos antes de tocar.",
                                "Execute, explique o dedilhado e só então confira a referência."),
                        List.of(variation("Três dedos", "Use apenas 1–2–3 para recuperar a forma.", -8, 3),
                                variation("Frase", "Crie uma resposta curta que termine em G.", 0, 3)), null),

                exercise("journey-drums-kit-map", "Responder pelo som certo no kit", "Mapa da bateria",
                        InstrumentId.DRUMS, "drum-kit-map", "imitate", 60, 72, 7,
                        "Ouvir o nome de uma peça e tocá-la sem cruzar o corpo ou procurar visualmente.",
                        "Kit ajustado; uma peça por pulso; sequência caixa–chimbal–bumbo–tom.",
                        "Duas sequências em ordem trocada sem atingir peça errada.",
                        List.of("Aponte e nomeie cada peça sem tocar.", "Toque a sequência fixa em semínimas.",
                                "Peça a sequência em ordem trocada e mantenha o pulso."),
                        List.of(variation("Três peças", "Use somente chimbal, caixa e bumbo.", -8, 3),
                                variation("Kit inteiro", "Inclua tom e surdo na ordem surpresa.", 0, 4)), null),
                exercise("journey-drums-body-pulse", "Pulso no corpo antes do kit", "Pulso para bateristas",
                        InstrumentId.DRUMS, "pulse", "listen", 60, 76, 6,
                        "Manter semínimas no pé e marcar 2 e 4 com as mãos.",
                        "Sem baquetas; 60 BPM; pé em quatro tempos e palmas em 2 e 4.",
                        "Oito compassos sem inversão das palmas e sem acelerar no silêncio.",
                        List.of("Marque somente o pé e conte 1–2–3–4.", "Acrescente palmas em 2 e 4.",
                                "Silencie o clique por um compasso e preserve as duas camadas."),
                        List.of(variation("Só pé", "Atravesse o silêncio apenas com o pé.", -8, 3),
                                variation("No kit", "Transfira pé para bumbo e palmas para caixa.", 0, 3)), null),
                exercise("journey-drums-hihat-eighths", "Colcheias iguais no chimbal", "Subdivisão no chimbal",
                        InstrumentId.DRUMS, "subdivisions", "slow", 56, 80, 8,
                        "Tocar oito colcheias equidistantes enquanto o pé marca semínimas.",
                        "56 BPM; chimbal fechado; dinâmica baixa; dois compassos tocando e um contando.",
                        "Três ciclos sem juntar o último 'e' ao pulso seguinte.",
                        List.of("Conte 1-e-2-e-3-e-4-e sem tocar.", "Adicione o pé nos números.",
                                "Toque o chimbal em todas as sílabas e grave a distância entre ataques."),
                        List.of(variation("Quatro ataques", "Toque somente os números e fale os 'e'.", -8, 3),
                                variation("Backbeat", "Acrescente caixa em 2 e 4.", 0, 5)), null),
                exercise("journey-drums-grip-rebound", "Deixar a baqueta voltar", "Pegada e rebote",
                        InstrumentId.DRUMS, "drum-grip", "compare", 60, 80, 7,
                        "Comparar pegada tensa e relaxada e produzir quatro rebotes equivalentes por mão.",
                        "Pad ou caixa; 60 BPM; quatro golpes por mão; volume médio.",
                        "Três séries por mão sem apertar após o impacto nem elevar o ombro.",
                        List.of("Faça um golpe e observe até onde a baqueta retorna.",
                                "Afrouxe polegar e indicador até o rebote aparecer.",
                                "Grave quatro golpes por mão e compare altura e volume."),
                        List.of(variation("Um golpe", "Espere o rebote terminar antes do próximo ataque.", -8, 3),
                                variation("Alternado", "Alterne R–L mantendo a mesma altura.", 0, 4)), null),
                exercise("journey-drums-one-beat-fill", "Virada curta que devolve o groove", "Virada de um tempo",
                        InstrumentId.DRUMS, "drum-one-beat-fill", "song", 60, 80, 10,
                        "Tocar três compassos de groove, uma virada no tempo 4 e voltar no 1.",
                        "60 BPM; virada R–L–R–L entre caixa e tons; quatro formas completas.",
                        "Quatro retornos com bumbo no primeiro tempo e sem pausa antes da virada.",
                        List.of("Toque quatro semicolcheias na caixa e pare no 1.",
                                "Distribua R–L–R–L entre caixa e tons.",
                                "Insira depois de três compassos e simplifique se o retorno atrasar."),
                        List.of(variation("Duas notas", "Use apenas duas colcheias no tempo 4.", -8, 4),
                                variation("Orquestração", "Passe por caixa, tom 1, tom 2 e surdo.", 0, 6)),
                        "Seven Nation Army drums play along"),
                exercise("journey-drums-rock-review", "Rock beat sem contagem externa", "Retenção de groove",
                        InstrumentId.DRUMS, "drum-rock-groove", "recall", 64, 84, 7,
                        "Reconstruir o rock beat de memória e sustentar oito compassos.",
                        "Sem partitura; contagem somente no primeiro compasso; nenhuma virada.",
                        "Oito compassos com caixa em 2 e 4 e último pulso alinhado ao clique.",
                        List.of("Descreva em voz alta a função de cada membro.", "Toque dois compassos sem partitura.",
                                "Grave oito compassos e confira início e fim contra o clique."),
                        List.of(variation("Duas camadas", "Retire o bumbo e estabilize chimbal e caixa.", -8, 3),
                                variation("Forma inteira", "Use oito compassos sem reiniciar após erro isolado.", 0, 4)),
                        "Billie Jean drums groove lento"));
    }

    static List<TeachingContentCatalog.Unit> units() {
        return List.of(
                unit("mission-guitar-pulse", InstrumentId.GUITAR, "Sentir o pulso dentro do riff", "pulse",
                        "journey-guitar-pulse-riff", 24, Assessment.Type.APPLICATION,
                        "Entrar e voltar ao riff sem perder a distância entre os pulsos.",
                        "O pulso será ouvido, marcado no corpo e levado a um riff de uma corda.",
                        "Riffs convincentes dependem tanto do espaço quanto das notas.",
                        "Quatro ciclos com retorno no tempo 1 e silêncio preservado.",
                        "Tentativa registrada e observação explícita sobre entrada e estabilidade.",
                        "Tocar o riff principal de Seven Nation Army em andamento reduzido.",
                        List.of("pulso", "continuidade", "retorno"),
                        List.of("seven-nation-army-guitar")),
                unit("mission-guitar-note-map", InstrumentId.GUITAR, "Encontrar notas sem decorar o braço inteiro", "notes",
                        "journey-guitar-note-landmarks", 22, Assessment.Type.FORMATIVE,
                        "Localizar E, A e C em pontos de referência do braço.",
                        "Poucas referências serão conectadas pelo som antes de ampliar o mapa.",
                        "Saber onde está a nota permite deslocar riffs e compreender acordes.",
                        "Seis localizações corretas em ordem misturada.",
                        "Respostas nomeadas e tocadas; erros permanecem registrados como lacunas.",
                        "Usar as notas de referência para localizar o início de um riff conhecido.",
                        List.of("nome-da-nota", "localizacao", "recuperacao"),
                        List.of("seven-nation-army-guitar")),
                unit("mission-guitar-subdivisions", InstrumentId.GUITAR, "Mudar a densidade sem mudar o tempo", "subdivisions",
                        "journey-guitar-eighth-riff", 25, Assessment.Type.APPLICATION,
                        "Alternar semínimas e colcheias mantendo a mesma caminhada.",
                        "A contagem continua igual enquanto a guitarra ocupa mais pontos entre os pulsos.",
                        "Controle de subdivisão torna riffs e bases legíveis para a banda.",
                        "Três formas completas sem acelerar nas colcheias.",
                        "Aplicação em riff com contagem audível e auto-observação contextual.",
                        "Aplicar a alternância a uma base simplificada de Zombie.",
                        List.of("pulso-base", "subdivisao", "troca-de-densidade"), List.of("zombie-guitar")),
                unit("mission-guitar-major-phrase", InstrumentId.GUITAR, "Fazer a escala chegar em casa", "major-scale",
                        "journey-guitar-major-home", 26, Assessment.Type.APPLICATION,
                        "Criar uma pergunta e resposta que faça a tônica soar como chegada.",
                        "A escala aparece como relação sonora, não como corrida por um desenho.",
                        "Ouvir a chegada ajuda a escolher notas com intenção.",
                        "Três respostas diferentes terminando em C após pausa clara.",
                        "Frases registradas com comparação entre tensão em B e repouso em C.",
                        "Improvisar uma introdução curta antes de um acompanhamento em C.",
                        List.of("referencia-tonal", "frase", "resolucao"), List.of()),
                unit("mission-guitar-harmonic-function", InstrumentId.GUITAR, "Ouvir o caminho dos acordes", "harmonic-field",
                        "journey-guitar-harmony-riff", 30, Assessment.Type.TRANSFER,
                        "Acompanhar I–IV–V–I com um motivo que reconhece cada função.",
                        "Teoria e ouvido serão ligados a uma pequena criação sobre acordes reais.",
                        "Função harmônica orienta riffs, solos e decisões de arranjo.",
                        "Duas voltas com chegada conjunta da frase e da harmonia.",
                        "Motivo aplicado ao loop e explicação do que mudou em cada acorde.",
                        "Transferir o motivo para o ciclo de quatro acordes de Zombie.",
                        List.of("funcao-ouvida", "aplicacao", "transferencia"), List.of("zombie-guitar")),
                unit("mission-guitar-pulse-review", InstrumentId.GUITAR, "Confirmar se o pulso permaneceu", "pulse",
                        "journey-guitar-pulse-review", 18, Assessment.Type.RETENTION,
                        "Retomar o riff no primeiro tempo depois de silêncio prolongado.",
                        "A revisão remove pistas visuais e verifica o que permaneceu disponível.",
                        "Relembrar em condição diferente é mais informativo que repetir logo após aprender.",
                        "Três retornos alinhados; marcar inconclusivo quando o áudio não permitir comparar.",
                        "Observação de retenção separada das tentativas iniciais.",
                        "Retomar Seven Nation Army sem contagem visual.",
                        List.of("pulso", "continuidade", "retorno"), List.of("seven-nation-army-guitar")),

                unit("mission-acoustic-pulse", InstrumentId.ACOUSTIC, "Manter a levada mesmo sem atacar", "pulse",
                        "journey-acoustic-pulse-strum", 23, Assessment.Type.FORMATIVE,
                        "Preservar o movimento contínuo da mão durante ataques e silêncios.",
                        "O pulso será sentido no braço antes de entrar em acordes.",
                        "Uma levada confiável não para quando a música pede espaço.",
                        "Quatro ciclos de som e silêncio sem quebrar o gesto.",
                        "Observação do retorno e da continuidade da mão.",
                        "Acompanhar a pulsação de A Horse with No Name com cordas abafadas.",
                        List.of("pulso", "continuidade", "retorno"), List.of("horse-no-name-acoustic")),
                unit("mission-acoustic-bass-map", InstrumentId.ACOUSTIC, "Usar baixos como mapa dos acordes", "notes",
                        "journey-acoustic-bass-roots", 22, Assessment.Type.FORMATIVE,
                        "Encontrar E, G, C e D nas cordas graves e antecipar a harmonia.",
                        "As notas serão aprendidas como raízes audíveis de acordes úteis.",
                        "O baixo certo orienta montagem, transposição e escuta do acompanhamento.",
                        "Duas voltas E–G–C–D sem busca por tentativa.",
                        "Nomes e localizações registrados na mesma tentativa.",
                        "Antecipar pelo baixo os acordes de Stand by Me.",
                        List.of("nome-da-nota", "localizacao", "recuperacao"), List.of("stand-by-me-acoustic")),
                unit("mission-acoustic-subdivisions", InstrumentId.ACOUSTIC, "Fazer a levada respirar em colcheias", "subdivisions",
                        "journey-acoustic-eighth-strum", 25, Assessment.Type.APPLICATION,
                        "Sustentar colcheias e acentuar 2 e 4 sem deformar o pulso.",
                        "A mão contínua será treinada primeiro abafada e depois em dois acordes.",
                        "Subdivisão clara mantém voz, acordes e banda no mesmo chão.",
                        "Oito compassos regulares com acentos audíveis.",
                        "Aplicação contínua em levada, sem depender de precisão automática.",
                        "Usar a célula em Have You Ever Seen the Rain.",
                        List.of("pulso-base", "subdivisao", "troca-de-densidade"), List.of("seen-rain-acoustic")),
                unit("mission-acoustic-major-melody", InstrumentId.ACOUSTIC, "Responder cantando e tocando", "major-scale",
                        "journey-acoustic-major-melody", 24, Assessment.Type.APPLICATION,
                        "Cantar uma resposta e encontrá-la no violão preservando ritmo e chegada.",
                        "O ouvido conduz o instrumento; a escala apenas delimita as opções.",
                        "Cantar antes de procurar reduz movimentos aleatórios e aproxima repertório real.",
                        "Duas respostas reproduzidas e concluídas em C.",
                        "Comparação honesta entre frase cantada e frase tocada.",
                        "Criar uma introdução de três notas sobre um acorde de C.",
                        List.of("referencia-tonal", "frase", "resolucao"), List.of()),
                unit("mission-acoustic-harmonic-cycle", InstrumentId.ACOUSTIC, "Entender o ciclo enquanto acompanha", "harmonic-field",
                        "journey-acoustic-harmonic-cycle", 30, Assessment.Type.TRANSFER,
                        "Acompanhar C–G–Am–F reconhecendo onde há repouso e movimento.",
                        "Os graus serão ouvidos dentro de uma forma usada por muitas canções.",
                        "Teoria ganha valor quando explica por que uma troca pede a próxima.",
                        "Quatro voltas com retorno claro a C e funções descritas.",
                        "Acompanhamento e explicação contextual observados juntos.",
                        "Relacionar o ciclo à estrutura de Stand by Me.",
                        List.of("funcao-ouvida", "aplicacao", "transferencia"), List.of("stand-by-me-acoustic")),
                unit("mission-acoustic-chords-review", InstrumentId.ACOUSTIC, "Confirmar os acordes sem cifra", "open-chords",
                        "journey-acoustic-chords-review", 18, Assessment.Type.RETENTION,
                        "Reconstruir Em e G e alterná-los depois de retirar o apoio visual.",
                        "A revisão separa lembrança real de reconhecimento imediato do desenho.",
                        "Acompanhamento exige acesso rápido às formas, não apenas familiaridade.",
                        "Quatro trocas no tempo com cordas previstas audíveis.",
                        "Evidência de retenção preservada separadamente da aula inicial.",
                        "Acompanhar uma seção de A Horse with No Name sem cifra.",
                        List.of("clareza", "chegada-no-tempo", "pulso"), List.of("horse-no-name-acoustic")),

                unit("mission-keys-pulse", InstrumentId.KEYS, "Sustentar o pulso em uma única nota", "pulse",
                        "journey-keys-pulse-note", 22, Assessment.Type.FORMATIVE,
                        "Manter semínimas e retornar depois de um compasso silencioso.",
                        "Uma nota libera atenção para distância, peso e retorno.",
                        "Pulso estável é a base para coordenar mãos e acompanhar outras pessoas.",
                        "Três retornos no primeiro tempo com volume uniforme.",
                        "Registro de estabilidade e retorno, sem análise automática inventada.",
                        "Levar o pulso ao riff de Seven Nation Army com uma mão.",
                        List.of("pulso", "continuidade", "retorno"), List.of("seven-nation-army-keys")),
                unit("mission-keys-note-map", InstrumentId.KEYS, "Ler o relevo do teclado", "notes",
                        "journey-keys-landmarks", 22, Assessment.Type.FORMATIVE,
                        "Encontrar C, F e G em três oitavas pela organização das teclas pretas.",
                        "O mapa nasce de referências visuais e sonoras, não de etiquetas permanentes.",
                        "Referências rápidas liberam atenção para leitura, frase e harmonia.",
                        "Nove localizações corretas em ordem misturada.",
                        "Resposta nomeada e tocada com erro observável.",
                        "Localizar as notas iniciais de Ode to Joy.",
                        List.of("nome-da-nota", "localizacao", "recuperacao"), List.of("ode-to-joy-keys")),
                unit("mission-keys-subdivisions", InstrumentId.KEYS, "Dar ritmos diferentes às mãos", "subdivisions",
                        "journey-keys-subdivision-hands", 26, Assessment.Type.APPLICATION,
                        "Manter semínimas na esquerda e colcheias na direita.",
                        "A coordenação será construída por funções rítmicas simples e reversíveis.",
                        "Independência começa quando uma mão não arrasta o pulso da outra.",
                        "Três séries de quatro compassos com a esquerda estável.",
                        "Aplicação bimanual observada em pulso e densidade.",
                        "Usar a esquerda como base para uma pequena melodia na direita.",
                        List.of("pulso-base", "subdivisao", "troca-de-densidade"), List.of()),
                unit("mission-keys-major-phrase", InstrumentId.KEYS, "Fazer cinco notas virarem frase", "major-scale",
                        "journey-keys-major-answer", 25, Assessment.Type.APPLICATION,
                        "Criar pergunta e resposta com pausa e chegada em C.",
                        "A escala será usada como vocabulário para uma forma curta e repetível.",
                        "Fraseado transforma exercício digital em música.",
                        "Duas execuções preservando ritmo, pausa e chegada.",
                        "Frase gravada ou observada, com comparação entre as duas voltas.",
                        "Variar uma frase de Ode to Joy sem perder o contorno.",
                        List.of("referencia-tonal", "frase", "resolucao"), List.of("ode-to-joy-keys")),
                unit("mission-keys-harmonic-functions", InstrumentId.KEYS, "Ouvir funções nas duas mãos", "harmonic-field",
                        "journey-keys-harmonic-functions", 30, Assessment.Type.TRANSFER,
                        "Tocar C–F–G–C com baixo e tríade e explicar sua direção.",
                        "A disposição simples entre as mãos deixa a função harmônica audível.",
                        "Compreender função permite acompanhar e depois escolher voicings melhores.",
                        "Quatro voltas e uma resolução cantada antes do acorde final.",
                        "Execução e explicação funcional ligadas à mesma tentativa.",
                        "Aplicar repouso, movimento e tensão aos acordes de Let It Be.",
                        List.of("funcao-ouvida", "aplicacao", "transferencia"), List.of("let-it-be-keys")),
                unit("mission-keys-five-review", InstrumentId.KEYS, "Levar a posição para outro ponto", "five-finger-position",
                        "journey-keys-five-review", 18, Assessment.Type.RETENTION,
                        "Reconstruir a posição de cinco dedos em G sem consultar a numeração.",
                        "A revisão muda a tônica para distinguir compreensão de memória espacial fixa.",
                        "Transferir uma forma mostra o que permaneceu disponível.",
                        "Três voltas uniformes e dedilhado explicado depois.",
                        "Observação de retenção e transferência sem promover domínio automaticamente.",
                        "Criar uma frase curta em G com a mesma organização de dedos.",
                        List.of("equilibrio", "forma", "continuidade"), List.of()),

                unit("mission-drums-kit-map", InstrumentId.DRUMS, "Conhecer o kit pelo gesto e pelo som", "drum-kit-map",
                        "journey-drums-kit-map", 22, Assessment.Type.FORMATIVE,
                        "Responder a nomes de peças com o som correto e postura estável.",
                        "O mapa físico será associado ao timbre e à função de cada peça.",
                        "Orientação segura evita movimentos desnecessários quando o groove começar.",
                        "Duas sequências trocadas sem peça errada.",
                        "Resposta observada no kit, com erros mantidos como informação.",
                        "Reconhecer onde vivem condução, backbeat, baixo e cores.",
                        List.of("peca-correta", "timbre", "postura"), List.of("we-will-rock-you-drums")),
                unit("mission-drums-pulse", InstrumentId.DRUMS, "Levar o pulso do corpo ao kit", "pulse",
                        "journey-drums-body-pulse", 20, Assessment.Type.FORMATIVE,
                        "Manter pé em semínimas e palmas em 2 e 4 inclusive no silêncio.",
                        "A coordenação começa fora do kit, com funções musicais fáceis de ouvir.",
                        "Sentir backbeat antes de tocar reduz correções mecânicas posteriores.",
                        "Oito compassos sem inverter 2 e 4 ou acelerar.",
                        "Observação rítmica corporal antes da execução instrumental.",
                        "Transferir pé para bumbo e palmas para caixa.",
                        List.of("pulso", "continuidade", "retorno"), List.of("we-will-rock-you-drums")),
                unit("mission-drums-subdivisions", InstrumentId.DRUMS, "Distribuir colcheias sem apertar o tempo", "subdivisions",
                        "journey-drums-hihat-eighths", 24, Assessment.Type.APPLICATION,
                        "Tocar colcheias iguais no chimbal com semínimas no pé.",
                        "A condução será montada por contagem, pé e mão antes do backbeat.",
                        "Colcheias regulares sustentam o espaço onde caixa e bumbo vão conversar.",
                        "Três ciclos sem comprimir o último 'e'.",
                        "Aplicação coordenada com distância entre ataques auto-observada.",
                        "Acrescentar caixa em 2 e 4 como preparação para o rock beat.",
                        List.of("pulso-base", "subdivisao", "troca-de-densidade"), List.of()),
                unit("mission-drums-grip", InstrumentId.DRUMS, "Usar o rebote em vez de força", "drum-grip",
                        "journey-drums-grip-rebound", 23, Assessment.Type.FORMATIVE,
                        "Produzir quatro golpes equivalentes por mão com pegada ajustável.",
                        "A comparação entre tensão e relaxamento torna o efeito do rebote perceptível.",
                        "Som consistente e resistência começam com uma pegada que não bloqueia a baqueta.",
                        "Três séries por mão sem perda visível de rebote.",
                        "Comparação gravada ou descrita entre as duas condições.",
                        "Transferir golpes alternados para caixa em um groove lento.",
                        List.of("rebote", "simetria", "tensao"), List.of()),
                unit("mission-drums-first-fill", InstrumentId.DRUMS, "Fazer uma virada e voltar no lugar", "drum-one-beat-fill",
                        "journey-drums-one-beat-fill", 30, Assessment.Type.PERFORMANCE,
                        "Inserir uma virada de um tempo depois de três compassos e retornar no 1.",
                        "A virada só será ampliada depois que a saída e o retorno estiverem claros.",
                        "Uma virada musical organiza a forma; não interrompe o groove.",
                        "Quatro formas completas com bumbo no primeiro tempo.",
                        "Tomada contínua com groove, virada e retorno observáveis.",
                        "Aplicar a virada entre seções de Seven Nation Army.",
                        List.of("entrada-da-virada", "orquestracao", "retorno-no-um"), List.of("seven-nation-army-drums")),
                unit("mission-drums-rock-review", InstrumentId.DRUMS, "Confirmar o rock beat sem partitura", "drum-rock-groove",
                        "journey-drums-rock-review", 19, Assessment.Type.RETENTION,
                        "Reconstruir o groove e sustentar oito compassos sem apoio visual.",
                        "A revisão retira a grade escrita e mantém apenas clique e memória da função.",
                        "Retenção confiável permite acompanhar uma música sem olhar o padrão o tempo todo.",
                        "Oito compassos com caixa em 2 e 4 e final alinhado.",
                        "Observação de retenção independente da primeira prática guiada.",
                        "Sustentar o groove principal de Billie Jean em andamento reduzido.",
                        List.of("pulso", "backbeat", "recuperacao"), List.of("billie-jean-drums")));
    }

    private static Exercise exercise(String id, String name, String technique, InstrumentId instrument,
                                     String competencyId, String activityType, int currentBpm, int targetBpm,
                                     int minutes, String objective, String conditions, String criteria,
                                     List<String> instructions, List<ExerciseVariation> variations,
                                     String practiceSongQuery) {
        var metronomic = currentBpm > 0;
        var current = metronomic ? currentBpm : 60;
        var target = metronomic ? targetBpm : 60;
        var exercise = new Exercise(id, name, technique, instrument, target, current, minutes, objective,
                competencyId, 2, metronomic ? Math.max(40, current - 12) : 40, 4, 80, 3,
                instructions, variations).withLearningResources(activityType, LearningStage.BEGINNER,
                technique + " " + instrument.value() + " demonstração lenta",
                "Aula da missão", null, "Observe a referência da aula antes de registrar a tentativa.",
                practiceSongQuery);
        exercise.configurePedagogicalDefinition(objective, conditions, criteria,
                new DifficultyDemand(2, 2, 2, 1, 1, 2, 1, 0, 2, 1, 1, 2, 1), List.of(competencyId));
        return exercise;
    }

    private static ExerciseVariation variation(String name, String instructions, int bpmOffset, int minutes) {
        return new ExerciseVariation(name, instructions, bpmOffset, minutes);
    }

    private static TeachingContentCatalog.Unit unit(
            String id, InstrumentId instrument, String title, String competencyId, String exerciseId,
            int minutes, Assessment.Type type, String objective, String context, String motivation,
            String completion, String evidence, String application, List<String> criteria,
            List<String> repertoireIds) {
        return new TeachingContentCatalog.Unit(id, instrument, LearningStage.BEGINNER, title, competencyId,
                lessonId(competencyId), List.of(exerciseId), minutes, objective, context, motivation,
                completion, evidence, application, "Observação: " + title,
                "Observar o resultado musical declarado sem converter autoavaliação em prova de domínio.",
                "Faça a atividade completa uma vez; escute ou reveja e descreva um momento concreto.",
                completion, "Contagem, metrônomo e referência da aula quando previstos.",
                "Se som, tempo ou observação não permitirem julgar um critério, marque inconclusivo e repita em outra sessão.",
                criteria, type, repertoireIds);
    }

    private static String lessonId(String competencyId) {
        return switch (competencyId) {
            case "major-scale" -> "escala-maior";
            case "harmonic-field" -> "campo-harmonico";
            default -> "lesson-" + competencyId;
        };
    }
}
